-- Extend the existing memory store in place; category sensitivity remains authoritative.
ALTER TABLE memories ADD COLUMN memory_type TEXT NOT NULL DEFAULT 'KNOWLEDGE' CHECK(memory_type IN ('PROFILE','PREFERENCE','KNOWLEDGE','HABIT','RELATIONSHIP','NOTE','CONTEXT','SYSTEM'));
ALTER TABLE memories ADD COLUMN memory_scope TEXT NOT NULL DEFAULT 'GLOBAL' CHECK(memory_scope IN ('GLOBAL','PROFILE','PET_PROFILE','SESSION','TEMPORARY'));
ALTER TABLE memories ADD COLUMN lifetime TEXT NOT NULL DEFAULT 'persistent' CHECK(lifetime IN ('persistent','session','temporary'));
ALTER TABLE memories ADD COLUMN importance REAL NOT NULL DEFAULT 0.6 CHECK(importance >= 0 AND importance <= 1);
ALTER TABLE memories ADD COLUMN confidence REAL NOT NULL DEFAULT 1.0 CHECK(confidence >= 0 AND confidence <= 1);
ALTER TABLE memories ADD COLUMN source TEXT NOT NULL DEFAULT 'MIGRATION' CHECK(source IN ('USER_MANUAL','COMMAND','SYSTEM','HABIT_ENGINE','IMPORT','MIGRATION','FUTURE_AI'));
ALTER TABLE memories ADD COLUMN last_accessed_at TEXT;
ALTER TABLE memories ADD COLUMN access_count INTEGER NOT NULL DEFAULT 0 CHECK(access_count >= 0);
ALTER TABLE memories ADD COLUMN expires_at TEXT;
ALTER TABLE memories ADD COLUMN session_id TEXT;
ALTER TABLE memories ADD COLUMN scope_id TEXT;
UPDATE memories SET memory_type='PROFILE', importance=1.0 WHERE memory_key='user.name';
UPDATE memories SET memory_type='NOTE', importance=0.7 WHERE category_id IN (SELECT id FROM memory_categories WHERE name='Important Notes') AND memory_key <> 'user.name';
CREATE INDEX memories_retrieval ON memories(memory_type, memory_scope, enabled);
CREATE INDEX memories_expiration ON memories(expires_at) WHERE expires_at IS NOT NULL;
CREATE INDEX memories_last_accessed ON memories(last_accessed_at);
CREATE TABLE memory_tags(id TEXT PRIMARY KEY, memory_id TEXT NOT NULL REFERENCES memories(id) ON DELETE CASCADE, tag TEXT NOT NULL, UNIQUE(memory_id,tag));
CREATE INDEX memory_tags_tag ON memory_tags(tag);
CREATE TABLE memory_aliases(id TEXT PRIMARY KEY, memory_id TEXT NOT NULL REFERENCES memories(id) ON DELETE CASCADE, alias TEXT NOT NULL, normalized_alias TEXT NOT NULL UNIQUE);
CREATE INDEX memory_aliases_memory ON memory_aliases(memory_id);
CREATE TABLE memory_relationships(id TEXT PRIMARY KEY, source_memory_id TEXT NOT NULL REFERENCES memories(id) ON DELETE CASCADE, relationship_type TEXT NOT NULL, target_memory_id TEXT NOT NULL REFERENCES memories(id) ON DELETE CASCADE, created_at TEXT NOT NULL, CHECK(source_memory_id <> target_memory_id), UNIQUE(source_memory_id,relationship_type,target_memory_id));
CREATE INDEX memory_relationships_target ON memory_relationships(target_memory_id);
CREATE TABLE habit_candidates(id TEXT PRIMARY KEY, candidate_type TEXT NOT NULL CHECK(candidate_type IN ('COMMAND','APPLICATION')), candidate_key TEXT NOT NULL UNIQUE, candidate_value TEXT NOT NULL, confidence REAL NOT NULL CHECK(confidence >= 0 AND confidence <= 1), evidence_count INTEGER NOT NULL CHECK(evidence_count >= 1), first_seen_at TEXT NOT NULL, last_seen_at TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING','ACCEPTED','REJECTED','EXPIRED')), rejected_at TEXT, memory_id TEXT REFERENCES memories(id) ON DELETE SET NULL);
CREATE INDEX habit_candidates_status ON habit_candidates(status);
INSERT OR IGNORE INTO memory_aliases SELECT lower(hex(randomblob(16))),id,'my name','my name' FROM memories WHERE memory_key='user.name' AND NOT EXISTS(SELECT 1 FROM memories WHERE lower(memory_key)='my name');
INSERT OR IGNORE INTO memory_aliases SELECT lower(hex(randomblob(16))),id,'name','name' FROM memories WHERE memory_key='user.name' AND NOT EXISTS(SELECT 1 FROM memories WHERE lower(memory_key)='name');
INSERT OR IGNORE INTO memory_aliases SELECT lower(hex(randomblob(16))),id,'user name','user name' FROM memories WHERE memory_key='user.name' AND NOT EXISTS(SELECT 1 FROM memories WHERE lower(memory_key)='user name');
INSERT OR IGNORE INTO memory_aliases SELECT lower(hex(randomblob(16))),id,'my browser','my browser' FROM memories WHERE memory_key='preferred.browser' AND NOT EXISTS(SELECT 1 FROM memories WHERE lower(memory_key)='my browser');
INSERT OR IGNORE INTO memory_aliases SELECT lower(hex(randomblob(16))),id,'default browser','default browser' FROM memories WHERE memory_key='preferred.browser' AND NOT EXISTS(SELECT 1 FROM memories WHERE lower(memory_key)='default browser');
INSERT OR IGNORE INTO memory_aliases SELECT lower(hex(randomblob(16))),id,'preferred browser','preferred browser' FROM memories WHERE memory_key='preferred.browser' AND NOT EXISTS(SELECT 1 FROM memories WHERE lower(memory_key)='preferred browser');
INSERT OR IGNORE INTO memory_aliases SELECT lower(hex(randomblob(16))),id,'my editor','my editor' FROM memories WHERE memory_key='preferred.editor' AND NOT EXISTS(SELECT 1 FROM memories WHERE lower(memory_key)='my editor');
INSERT OR IGNORE INTO memory_aliases SELECT lower(hex(randomblob(16))),id,'my code editor','my code editor' FROM memories WHERE memory_key='preferred.editor' AND NOT EXISTS(SELECT 1 FROM memories WHERE lower(memory_key)='my code editor');
INSERT OR IGNORE INTO memory_aliases SELECT lower(hex(randomblob(16))),id,'preferred editor','preferred editor' FROM memories WHERE memory_key='preferred.editor' AND NOT EXISTS(SELECT 1 FROM memories WHERE lower(memory_key)='preferred editor');
INSERT OR IGNORE INTO memory_aliases SELECT lower(hex(randomblob(16))),id,'default editor','default editor' FROM memories WHERE memory_key='preferred.editor' AND NOT EXISTS(SELECT 1 FROM memories WHERE lower(memory_key)='default editor');
INSERT OR IGNORE INTO memory_aliases SELECT lower(hex(randomblob(16))),id,'preferred.code_editor','preferred.code_editor' FROM memories WHERE memory_key='preferred.editor' AND NOT EXISTS(SELECT 1 FROM memories WHERE lower(memory_key)='preferred.code_editor');
PRAGMA user_version = 3;
