"""Native Stitch workflow composition, independent of routine execution logic."""
from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import QWidget, QFrame, QVBoxLayout, QHBoxLayout, QFormLayout, QLineEdit, QPlainTextEdit, QSplitter, QListWidget, QAbstractItemView, QGridLayout, QComboBox, QDoubleSpinBox
from ...core.workflows import STEP_LABELS
from .widgets import ComboBox as QComboBox
from .widgets import label, card, button, actions, ResponsiveRow, Toggle

def build(self):
    root = QVBoxLayout(self)
    root.setContentsMargins(0, 0, 0, 0);root.setSpacing(16)
    header, header_layout = card()
    title = QWidget()
    title_layout = QVBoxLayout(title)
    title_layout.setContentsMargins(0, 0, 0, 0)
    title_layout.addWidget(label('AUTOMATIONS  /  ROUTINE BUILDER', 'eyebrow'))
    title_layout.addWidget(label('Workflows', 'heading'))
    title_layout.addWidget(label('Build your routine once. Start it with a phrase or the Run button.', 'muted'))
    self.save_button = button('Save', self.save, True, 'save')
    self.run_button = button('Run routine', self.run, icon='play_arrow')
    self.stop_button = button('Stop', self.controller.stop_routine, icon='stop')
    toolbar = QWidget()
    toolbar_layout = QVBoxLayout(toolbar)
    toolbar_layout.setContentsMargins(0, 0, 0, 0)
    toolbar_layout.addWidget(actions([self.save_button, self.run_button, self.stop_button]), 0, Qt.AlignmentFlag.AlignRight)
    self.notice = label('Create a routine or choose one from the list.', 'notice')
    toolbar_layout.addWidget(self.notice)
    self.header_row = ResponsiveRow(self.manager, (title, toolbar), (3, 2))
    header_layout.addWidget(self.header_row)
    root.addWidget(header)
    self.splitter = splitter = QSplitter(Qt.Orientation.Horizontal)
    splitter.setChildrenCollapsible(False);splitter.setHandleWidth(16)
    self.compact = None
    root.addWidget(splitter, 1)
    self.library, lib = card('Routine library')
    self.search = QLineEdit();self.search.setPlaceholderText('Search routines')
    self.search.textChanged.connect(self.refresh_library)
    lib.addWidget(self.search)
    self.routines = QListWidget();self.routines.setObjectName('routineLibrary')
    self.routines.currentItemChanged.connect(self.select_routine)

    self.new_button = button('New routine', lambda: self.new_draft(), True, 'add')
    self.template_button = button('Start Work template', self.template, icon='account_tree')
    self.duplicate_button = button('Duplicate', self.duplicate, icon='content_copy')
    self.delete_button = button('Delete', self.delete, icon='delete')
    self.toggle_button = button('Enable / Disable', self.toggle, icon='check_circle')
    self.library_actions = (self.new_button, self.template_button, self.duplicate_button, self.delete_button, self.toggle_button)
    self.library_buttons = QGridLayout()
    for i, control in enumerate(self.library_actions): self.library_buttons.addWidget(control, i, 0)
    lib.addLayout(self.library_buttons)
    lib.addWidget(self.routines, 1)
    splitter.addWidget(self.library)
    right = QWidget();layout = QVBoxLayout(right)
    layout.setContentsMargins(0, 0, 0, 0);layout.setSpacing(16)
    self.editor = QWidget();edit = QVBoxLayout(self.editor)
    edit.setContentsMargins(0, 0, 0, 0)
    self.body_layout = body = QHBoxLayout();body.setSpacing(16)
    center = QWidget();center_layout = QVBoxLayout(center)
    center_layout.setContentsMargins(0, 0, 0, 0);center_layout.setSpacing(16)
    identity, identity_layout = card('Routine & triggers')
    form = QFormLayout();form.setRowWrapPolicy(QFormLayout.RowWrapPolicy.WrapAllRows)
    self.name = QLineEdit();self.name.setMaxLength(150);self.name.setPlaceholderText('Routine name')
    self.phrases = QPlainTextEdit();self.phrases.setMaximumHeight(72)
    self.phrases.setPlaceholderText('Trigger phrases, one per line\nstart work')
    self.enabled = Toggle('Enabled')
    form.addRow('Routine name', self.name);form.addRow('Trigger phrases', self.phrases);form.addRow(self.enabled)
    identity_layout.addLayout(form);center_layout.addWidget(identity)
    canvas, flow = card()
    trigger = label('Input event trigger', 'eyebrow');flow.addWidget(trigger)
    self.canvas = QListWidget();self.canvas.setObjectName('workflowCanvas')
    self.canvas.setMinimumHeight(280);self.canvas.setWordWrap(True)
    self.canvas.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
    self.canvas.setDragDropMode(QAbstractItemView.DragDropMode.InternalMove)
    self.canvas.setDefaultDropAction(Qt.DropAction.MoveAction)
    self.canvas.currentRowChanged.connect(self.select_step)
    self.canvas.model().rowsMoved.connect(self.reordered)
    flow.addWidget(self.canvas, 1)
    flow.addWidget(label('Routine complete · companion returns to idle', 'muted'))
    self.step_count = label('Step limit: 0 / 50', 'muted');flow.addWidget(self.step_count)
    self.add_step_button = button('Add Step', self.add_step, icon='add')
    flow.addWidget(actions([self.add_step_button,
        button('Move Up', lambda: self.move_step(-1)), button('Move Down', lambda: self.move_step(1)),
        button('Remove', self.remove_step, icon='delete')]))
    center_layout.addWidget(canvas, 1);body.addWidget(center, 3)
    self.settings = QFrame();self.settings.setObjectName('card')
    self.step_form = QFormLayout(self.settings)
    self.step_form.setContentsMargins(20, 20, 20, 20);self.step_form.setSpacing(12)
    self.step_form.setRowWrapPolicy(QFormLayout.RowWrapPolicy.WrapAllRows)
    self.step_form.addRow(label('Step settings', 'subheading'))
    self.type = QComboBox()
    for kind, title in STEP_LABELS.items(): self.type.addItem(title, kind)
    self.application = QComboBox();self.value = QLineEdit()
    self.browse = button('Choose folder…', self.choose_path, icon='folder_open')
    self.seconds = QDoubleSpinBox();self.seconds.setRange(0, 90);self.seconds.setDecimals(2);self.seconds.setSuffix(' seconds')
    self.step_form.addRow('Action type', self.type);self.step_form.addRow('Application', self.application)
    self.step_form.addRow('Target / message', self.value)
    self.url_hint = label('Enter a website such as example.com or https://example.com. HTTPS is used automatically.', 'muted')
    self.step_form.addRow(self.url_hint)
    self.file_hint = label('Opens with the default Windows app for this file.', 'muted');self.step_form.addRow(self.file_hint)
    self.step_form.addRow(self.browse);self.step_form.addRow('Wait', self.seconds)
    body.addWidget(self.settings, 2, Qt.AlignmentFlag.AlignTop)
    edit.addLayout(body, 1);layout.addWidget(self.editor, 1)
    self.progress = label('', 'notice');layout.addWidget(self.progress)
    splitter.addWidget(right);splitter.setSizes([220, 700])
